_format_version: "3.0"
_transform: true

services:
  - name: auth-service
    url: http://host.docker.internal:8081/auth
    routes:
      - name: auth-route
        paths:
          - /api/auth
        strip_path: true
  - name: transaction-service
    url: http://host.docker.internal:8084/transfers
    routes:
      - name: transfer-route
        paths:
          - /api/transfers
        strip_path: true

consumers:
  - username: alice
    jwt_secrets:
      - algorithm: HS256
        key: alice
        secret: test-secret-for-auth-service

plugins:
  - name: jwt
    service: transaction-service
    config:
      key_claim_name: sub
      claims_to_verify:
        - exp
      header_names:
        - authorization
