spring.application.name=fraud-detection-service
server.port=8083
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
logging.pattern.level=%5p [${spring.application.name:app},traceId:%X{traceId:-},spanId:%X{spanId:-},requestId:%X{requestId:-}]
