server.port=8084
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/transaction_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:banking}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:banking}
spring.jpa.hibernate.ddl-auto=update
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
integration.account-service.base-url=http://localhost:8082
integration.fraud-service.base-url=http://localhost:8083
