server.port=8082
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/account_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:banking}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:banking}
spring.jpa.hibernate.ddl-auto=update
